/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.pshevche;

import org.testng.annotations.*;

@Listeners(LoggingListener.class)
public class AfterClassTest {

    @BeforeClass
    public void setupClass() {
    }

    @AfterClass
    public void cleanupClass() {
    }

    @Test
    public void test1() {
    }

}
